#/appspec.yml
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build
hooks:
  BeforeInstall:
    - location: /initialize.sh
      runas: root
 
  AfterInstall:
    - location: /after_start.sh
      runas: root

  ApplicationStart:
    - location: /start.sh
      runas: root
